name: Frontend CI/CD

on:
  push:
    paths:
      - 'webapp/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        cd webapp
        npm install

    - name: Run tests
      run: |
        cd webapp
        npm test

    - name: Build Docker image
      run: |
        cd webapp
        docker build -t ecommerce-frontend .
